# Generated by Django 5.1.1 on 2024-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_attendant',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=3),
        ),
    ]
