# Generated by Django 5.1.1 on 2024-10-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_alter_lab_attendant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_attendant',
            name='labaratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='computer.labaratory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lab_attendant',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lab_attendant',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lab_attendant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='labaratory',
            name='number_of_computers',
            field=models.IntegerField(),
        ),
    ]
